### ISSUE TITLE
copy:build_themes

### ISSUE THREAD

**Issue by markusbrunner-design** [Open-Xchange-Frontend/shared-grunt-config#1]
Hallo Julian,

the task "copy:build_themes" is not present any more and therefore is throwing an error message on usage.

Regards
Markus

**Comment by johnyb** [comment]
Yes, this is, because it is not needed any longer. This has never been public API anyways and is now handled by `copy:build_app`. See 15b39a25de52a2b465b2088c4bafe3337ccc5786 for details.

If, for some reason, you really need this task, you can implement it for your repository by overriding default behaviour. Just put some grunt-configuration files into `grunt/tasks/` and they will be picked up. See [this article](http://johnyb.github.io/2014/05/10/extending_shared_grunt_configuration.html) for details (quite old but still most points are valid).
