### ISSUE TITLE
dist:source task unable to write due to EISDIR error

### ISSUE THREAD

**Issue by mandibuswell** [Open-Xchange-Frontend/shared-grunt-config#2]
I am running version 0.11.3 and following the instructions in the getting started and related wiki articles.
https://oxpedia.org/wiki/index.php?title=AppSuite:GettingStarted_7.6.0

Everytime I run grunt dist:source --include-dependencies  i am getting an 
Warning: Unable to write "dist/owm-spark-gui2-0.0.0/apps/com.example" file (Error code: EISDIR)

User verbose I can see the following:

Running "copy:source" (copy) task
Verifying property copy.source exists in config...OK
Files: apps/com.example, apps/com.example/manifest.json, apps/com.example/register.js, Gruntfile.js, .jshintrc, bower.json, package.json -> dist/owm-spark-gui2-0.0.0/
Options: encoding="utf8", processContent=false, processContentExclude=[], timestamp=false, mode=false
Creating dist/owm-spark-gui2-0.0.0/apps/com.example
Copying apps/com.example/manifest.json -> dist/owm-spark-gui2-0.0.0/apps/com.example
Reading apps/com.example/manifest.json...OK
Writing dist/owm-spark-gui2-0.0.0/apps/com.example...ERROR
Warning: Unable to write "dist/owm-spark-gui2-0.0.0/apps/com.example" file (Error code: EISDIR). Use --force to continue.

This appears like it is trying to copy the source file to the destination directory name and not the filename.

**Comment by johnyb** [comment]
Released v0.11.4 via npm, please update to the latest version and try the `dist:source` task, again. At least on my machine it works fine, now. I'm running openSUSE, so I tried building an RPM package. It worked quite fine. I just had to adjust the generated script in the spec file a bit, due to incompatibilities with node 0.12. To be on the safe side, please use node 0.10, for now. (Until the node community decides, which way to go.)
