### ISSUE TITLE
Can't find lots of files when watching

### ISSUE THREAD

**Issue by binarykitchen** [Open-Xchange-Frontend/shared-grunt-config#4]
```
Done, without errors.
Completed in 2.705s at Wed Apr 13 2016 14:37:50 GMT+1200 (NZST) - Waiting...
localfile not found:  /core
localfile not found:  /apps/themes/login/login.css
localfile not found:  /boot.js
localfile not found:  /precore.js
localfile not found:  /boot.js.map
localfile not found:  /apps/themes/default/favicon.ico
localfile not found:  /apps/themes/default/favicon.ico
localfile not found:  /static/3rd.party/Chart.js/Chart.js
```

this after `grunt dev`. Any ideas why?

**Comment by johnyb** [comment]
Yes, this is expected, because this is not an error per se. Seems you activated debug messages for the local appserver proxy. If those files are not found locally, they will be fetched from the server specified in `grunt/local.conf.json`. If you also see such messages in the browser, there is something wrong with your configuration.

https://oxpedia.org/wiki/index.php?title=AppSuite:UI might help you getting started in any case. Also the tutorials on http://dev.ox.io/tutorials/ might be worth a look.

Just a side note: this is not a support forum, but an issue tracker. We are closing issues, which are not issues of the project itself.

**Comment by binarykitchen** [comment]
ok, thanks. is there a support forum where i can ask those questions?

**Comment by johnyb** [comment]
As far as I know, there is no official way to get support any longer. Many issues should be covered in the FAQ:

[here](https://oxpedia.org/wiki/index.php?title=AppSuite:UI_FAQ) for general questions about UI, [here](https://oxpedia.org/wiki/index.php?title=AppSuite:GruntFAQ) for questions about the build environment.

Then there is https://forum.open-xchange.com/, where you might find help.

**Comment by johnyb** [comment]
BTW, if you have specific issues or suggestions for improvement of this software (even documentation issues). Contributing to this project is one way to get those fixed.
